### ISSUE TITLE
No Shared Memory

### ISSUE THREAD

**Issue by jbmcgee** [bloodelves88/CloudyNvCapture#7]
Trying with NvIFR. Any thoughts on the shared memory error? I get the same with the dxifrshim example from the sdk. Also, once working, how do you play the stream with ffplay/vlc if i'm streaming on 127.0.0.1:30000?
```
[DEBUG][14:25:21] No shared memroy to open (no shared memory name in environment variable).
[DEBUG][14:25:21] CreateDXGIFactory1_Proxy
[DEBUG][14:25:21] IDXGIFactory_EnumAdapters_Proxy
[INFO ][14:25:21] Only one adapter found. Using it without further checks.
[DEBUG][14:25:21] CreateDXGIFactory_Proxy
[DEBUG][14:25:21] CreateDXGIFactory1_Proxy
[DEBUG][14:25:21] IDXGIFactory_EnumAdapters_Proxy
[INFO ][14:25:21] Only one adapter found. Using it without further checks.
[DEBUG][14:25:21] IDXGIFactory_EnumAdapters_Proxy
[INFO ][14:25:21] Only one adapter found. Using it without further checks.
[DEBUG][14:25:21] CreateDXGIFactory_Proxy
[DEBUG][14:25:21] CreateDXGIFactory1_Proxy
[DEBUG][14:25:21] IDXGIFactory_EnumAdapters_Proxy
[INFO ][14:25:21] Only one adapter found. Using it without further checks.
[DEBUG][14:25:21] IDXGIFactory_EnumAdapters_Proxy
```

**Comment by ngsp94** [comment]
Hi,

I've only tried with DXIFRShim so I can't say for any other examples.

Make sure you have NVIDIA Grid, since you need it to run shim. You can see if the ffmpeg debug log gives you any useful errors. Enable the debug log in NvHWEncoder.cpp by adding ```<< " 2> log.txt"``` to the end of the ffmpeg streaming command somewhere around line 893.

I haven't had the stream work with anything other than MPlayer. With MPlayer you can run
```
mplayer -demuxer h264es http://127.0.0.1:30000
```
and it should work.

Hope to have been of help!
